// <auto-generated />
namespace bookly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class seedingCustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedingCustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "202104282301123_seedingCustomers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
